export HOST = 'bkvr6afh90lntut7zlay-mysql.services.clever-cloud.com'
export DATABASE = 'bkvr6afh90lntut7zlay'
export PASSWORD = 'bAiGtlCuannbB7tZDT6T'
export USERDB = 'uccyyf00d6p1cs9k'
export SENDGRID_API_KEY = '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'